name: FreeyaAuerinCatherine_app_dart
description: A Library Full Package Template
version: 0.0.0
homepage: https://github.com/FreeyaAuerinCatherine/FreeyaAuerinCatherine_app
repository: https://github.com/FreeyaAuerinCatherine/FreeyaAuerinCatherine_app
issue_tracker: https://github.com/FreeyaAuerinCatherine/FreeyaAuerinCatherine_app/issues 
documentation: https://youtube.com/@FreeyaAuerinCatherine
funding:
  - https://github.com/sponsors/FreeyaAuerinCatherine


platforms:
 android:
 ios:
 linux:
 macos:
 web:
 windows:

# topics:
#   - FreeyaAuerinCatherine_app
#   - FreeyaAuerinCatherine_app_flutter
#   - FreeyaAuerinCatherine_app_dart

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
